### ISSUE TITLE
linking problem in opam install

### ISSUE THREAD

**Issue by disteph** [LaurentMazare/ocaml-torch#11]
I get the following linking error when doing `opam install torch`
Does the message happen to ring a bell?
I'm on opam 2.02, testing opam switches 4.06.1+fp+flambda as well as 4.07.0+fp+flambda, linux Ubuntu 18.10.
I had got quite excited by the simplicity of the install :-)

```<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>
∗ installed sexplib.v0.11.0
[ERROR] The compilation of torch failed at "/home/graham-lengrand/.opam/opam-init/hooks/sandbox.sh build dune build -p torch -j 4".

#=== ERROR while compiling torch.0.3 ==========================================#
# context     2.0.2 | linux/x86_64 | base-bigarray.base base-threads.base base-unix.base ocaml-variants.4.06.1+fp+flambda | https://opam.ocaml.org/#421079ff
# path        ~/.opam/4.06.1+fp+flambda/.opam-switch/build/torch.0.3
# command     ~/.opam/opam-init/hooks/sandbox.sh build dune build -p torch -j 4
# exit-code   1
# env-file    ~/.opam/log/torch-29671-3e450d.env
# output-file ~/.opam/log/torch-29671-3e450d.out
### output ###
#   ocamlmklib src/wrapper/dlltorch_core_stubs.so,src/wrapper/libtorch_core_stubs.a (exit 2)
# (cd _build/default && /home/graham-lengrand/.opam/4.06.1+fp+flambda/bin/ocamlmklib.opt -g -o src/wrapper/torch_core_stubs src/wrapper/torch_stubs.o src/wrapper/torch_api.o -lstdc++ -Wl,-rpath,/home/graham-lengrand/.opam/4.06.1+fp+flambda/lib/libtorch/lib -L/home/graham-lengrand/.opam/4.06.1+fp+flambda/lib/libtorch/lib -lc10 -lcaffe2 -ltorch)
# /usr/bin/ld: src/wrapper/torch_api.o: relocation R_X86_64_PC32 against symbol `_ZN3c105ErrorD1Ev' can not be used when making a shared object; recompile with -fPIC
# /usr/bin/ld: final link failed: bad value
# collect2: error: ld returned 1 exit status
```

**Comment by LaurentMazare** [comment]
Seems that it's missing the -fPIC option (which for some platform is necessary). I only added it in this [commit](https://github.com/LaurentMazare/ocaml-torch/commit/64483bc95154b19ecb367c60e36887a149bc4f9f#diff-f9bf7af9c4d007ef31de59591c6cd877) but I don't think I've made a new opam package since then.
Can you try using the current github tip ? I would hope for this to work.

**Comment by disteph** [comment]
Stupid me, I could have checked the diff between HEAD and the opam package version.
It worked like a charm.
I'll unpin my local opam package from the github URL as soon as the opem repo is updated...

**Comment by LaurentMazare** [comment]
Closing this as it should be all fixed now, feel free to re-open if useful.
