### ISSUE TITLE
examples/mnist/dune torch_core dependency

### ISSUE THREAD

**Issue by zeroexcuses** [LaurentMazare/ocaml-torch#14]
https://github.com/LaurentMazare/ocaml-torch/blob/master/examples/mnist/dune refers to torch_core

```
cat dune; echo "==="; dune build mnist_linear.exe
(executable
 (name mnist_linear)
 (libraries base torch_core torch stdio))

===
File "dune", line 3, characters 17-27:
3 |  (libraries base torch_core torch stdio))
                     ^^^^^^^^^^
Error: Library "torch_core" not found.
Hint: try: dune external-lib-deps --missing mnist_linear.exe

```

However, when I try to find torch_core

```
opam search torch_core
# Packages matching: match(*torch_core*)
# No matches found

```

It seems this module does not exist.

**Comment by LaurentMazare** [comment]
This module is defined in `src/wrapper/dune` in the github repo, if you look at the dune file there it's public name is `torch.core` which gets automatically installed when you install the main `torch` package.
Are you're trying to build this example inside the github repo?
If not maybe replacing this with `torch.core` in the dune file would work better.

**Comment by zeroexcuses** [comment]
1. Yes, I was running it outside of the github repo.

2. Changing it to torch.core seems to have fixed the issue.

Thanks!
