### ISSUE TITLE
custom functions with user defined backward passes?

### ISSUE THREAD

**Issue by zeroexcuses** [LaurentMazare/ocaml-torch#19]
Source: https://pytorch.org/tutorials/beginner/examples_autograd/two_layer_net_custom_function.html

We discussed this already for Rust.

Does OCaml bindings have the same limitations of not supporting user-defined functions with custom backward passes?

**Comment by LaurentMazare** [comment]
It's the same as for rust I'm afraid, https://github.com/LaurentMazare/tch-rs/issues/70
I'm not sure if the C++ PyTorch api supports it, if that's the case it may not be too hard to add to the rust/ocaml bindings but it seems that it's a pretty rare use case so I haven't found much need for it.

**Comment by zeroexcuses** [comment]
I think you're right, now that I think more over this, it seems that in any situation where I care enough to write a custom backward pass, I'd probably care enough to write custom cuda kernels for both passes -- so just doing a custom backward pass (with existing Tensor primitives) seems unlikely.
