### ISSUE TITLE
Request For Advise :-)

### ISSUE THREAD

**Issue by zbroyar** [LaurentMazare/ocaml-torch#26]
Hi Laurent,

I'd like to play with reinforced learning and OCaml with aim to create working A3C model for my task. Which binding would you recommend for it? Tensorflow of Torch?

Thanks in advance :-)

**Comment by LaurentMazare** [comment]
I would recommend using the torch bindings.
There are already a bunch of reinforcement learning examples that could be handy, including A2C. These are applied to atari games (via the openai gym) but can easily be extended to other settings. You can find the example code [here](https://github.com/LaurentMazare/ocaml-torch/blob/master/examples/reinforcement-learning/a2c.ml).

**Comment by zbroyar** [comment]
Thanks a lot, appreciate it.
