### ISSUE TITLE
Linking error during "make all" (during alternative installation Option 1)

### ISSUE THREAD

**Issue by Kwonsoo** [LaurentMazare/ocaml-torch#29]
Hi,

I am trying to follow the instruction for the alternative installation option 1 described in Github README.

I downloaded libtorch from pytorch.org, with the setting Stable(1.3) / Linux / LibTorch / C++ / 10.1 and by clicking https://download.pytorch.org/libtorch/cu101/libtorch-shared-with-deps-1.3.1.zip.
Then, I unzipped the directory at ~/lib/libtorch. Then,

> export LIBTORCH=~/lib/libtorch
> git clone https://github.com/LaurentMazare/ocaml-torch.git
> cd ocaml-torch
> make all

When I run "make all", the error messages related to linking are printed. The messages are too long, and so I attach a file for the messages:
[error_gpu_makeall.txt](https://github.com/LaurentMazare/ocaml-torch/files/3954422/error_gpu_makeall.txt)

The current setup is as follows:
- OS: Ubuntu 16.04 LTS
- Opam version: 2.0.5
- Ocaml compiler version: 4.07.0
- gcc version: 8.3.0

Thanks in advance!

Best,
Gwonsoo

**Comment by LaurentMazare** [comment]
I think the default is now to use the C++11 ABI, could you try downloading the following file instead and see if it works better ? (don't forget to do a `make clean` before running `make all` again)
https://download.pytorch.org/libtorch/cu101/libtorch-cxx11-abi-shared-with-deps-1.3.1.zip

**Comment by Kwonsoo** [comment]
Now it works!
I should have tried the alternative.

Also, for other users:
When running e.g., MNIST linear example after compile through "_build/default/examples/mnist/linear.exe", one might see another error message shown below.

> Fatal error: exception Unix.Unix_error(Unix.ENOENT, "open", "data/t10k-labels-idx1-ubyte")
> Raised by primitive operation at file "src/torch/dataset_helper.ml", line 4, characters 11-57
> Called from file "src/torch/mnist_helper.ml", line 27, characters 16-56
> Called from file "src/torch/mnist_helper.ml", line 40, characters 18-65
> Called from file "examples/mnist/linear.ml", line 18, characters 4-30

This is because the ocaml-torch directory does not come with the full dataset, and so one needs to download the proper dataset files (from http://yann.lecun.com/exdb/mnist/ for MNIST, for example) and put them in the data/ directory before actually running the examples.

Thank you very much for your help, Laurent!

Best,
Gwonsoo
