### ISSUE TITLE
Build (gcc) error for MNIST linear example

### ISSUE THREAD

**Issue by Kwonsoo** [LaurentMazare/ocaml-torch#30]
Hi,

I have succeeded to install the library through opam ("opam install torch"), and to run the simple print example described in https://github.com/LaurentMazare/ocaml-torch using dune ("dune exec src/example.exe").
The problem is when I try to run the linear classifier for MNIST (examples/mnist/linear.ml), again, using dune ("dune exec examples/mnist/linear.exe"),
I see some errors related to gcc and torch C++ API.

The relevant specs are as follows:
- Ubuntu 16.04 LTS
- Opam version: 2.0.5
- I tried two Ocaml compiler versions, 4.06.0 and 4.07.0 (and both led to nearly same error messages).
- gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609  (* When I used gcc 7.4.0, the similar error mesages were printed.)

The length of the error messages are too long, and so I attach two separate files for the error messages, one for Ocaml 4.06.0 and the other for Ocaml 4.07.0:
[error_log_4.06.0.txt](https://github.com/LaurentMazare/ocaml-torch/files/3954611/error_log_4.06.0.txt)
[error_log_4.07.0.txt](https://github.com/LaurentMazare/ocaml-torch/files/3954612/error_log_4.07.0.txt)

Thanks in advance!

Best,
Gwonsoo

**Comment by LaurentMazare** [comment]
This one looks like a version mismatch. The opam package is I think currently using PyTorch 1.2.0, I'll craft a new opam release for PyTorch 1.3.1.

**Comment by Kwonsoo** [comment]
Now it works after running "opam remove libtorch" followed by "opam install libtorch".
The libtorch version that opam has installed is now 1.3.1 (instead of 1.2.0).

Thank you so much, Laurent.

Best,
Gwonsoo
