### ISSUE TITLE
Support for probability distributions

### ISSUE THREAD

**Issue by Kwonsoo** [LaurentMazare/ocaml-torch#35]
Hi,

It seems to me that ocaml-torch does not provide API for torch.distributions.
Specifically, it does not implement various probability distributions with some common functions such as sample and log_prob.
I think they are important enough and should be implemented here.

Best,
Gwonsoo

**Comment by LaurentMazare** [comment]
Hi,
Right I agree that it would be a nice thing to add. The modules from torch.distributions are mostly written in python so this would have to be re-implemented on the ocaml side, the required torch primitives should already be exposed.

**Comment by Kwonsoo** [comment]
Do you have any specific plans for implementing them?

**Comment by LaurentMazare** [comment]
Not currently, I can add it to my stack but I'm unsure when I'll get to it. Feel free to have a go at it if you want.
Do you have some use cases for this? Also knowing which distributions are the most interesting ones could be helpful.

**Comment by Kwonsoo** [comment]
My colleagues and I are working on some variational inference-like optimization procedure, and the objective function we are considering involves distance (e.g., KL-divergence) between two different probability distributions. To backpropagate through such an objective, we need to be able to evaluate the probability densities or masses of the distributions we consider.

Currently we are focusing only on normal distributions (to simplify the setting), but we may want to consider more other distributions later. I have little idea on what specific distributions we may be going to be interested, but maybe some popular distributions used a lot in statistics (such as normal, beta, gamma, etc.) including the ones pops up often in Pytorch and Pyro examples.

**Comment by Kwonsoo** [comment]
Hi Laurent,

I re-opened this issue, and I think it will be helpful for many users if `ocaml-torch` supports at least normal distributions and multivariate normal distributions (sample and log_prob functions). Normal distributions are easy to implement, but multivariate normal distributions seem to need more care.

Thanks,
Gwonsoo
