### ISSUE TITLE
Is there a regressor example in there?

### ISSUE THREAD

**Issue by UnixJunkie** [LaurentMazare/ocaml-torch#37]
I could not find one. :(

**Comment by LaurentMazare** [comment]
What do you mean by regressor ?
If it's a linear regression that you're after, I think the closest thing is the [optimizer test](https://github.com/LaurentMazare/ocaml-torch/blob/64dd606157b953ba9cbf4d6a03d47611961e60fa/src/tests/optimizer_tests.ml). Let me know if you have any question/want more details.

**Comment by UnixJunkie** [comment]
Something to predict a scalar, instead of a class label.

**Comment by LaurentMazare** [comment]
Ok, then the linear regression example above should indeed do this.

**Comment by LaurentMazare** [comment]
Closing as no further activity in a while, feel free to re-open if useful.
