### ISSUE TITLE
Warning when running the char_rnn example

### ISSUE THREAD

**Issue by jonathan-laurent** [LaurentMazare/ocaml-torch#40]
When running the `char_rnn` example:

```
dune exec examples/char_rnn/char_rnn.exe
```

I get the following warning repeatedly (probably once per training batch):

```
Warning: RNN module weights are not part of single contiguous chunk of memory.
This means they need to be compacted at every call, possibly greatly increasing memory usage.
To compact weights again call flatten_parameters().
(_cudnn_impl at ../aten/src/ATen/native/cudnn/RNN.cpp:1269)
```

I am not sure how much it impacts training speed. Right now, each training epoch takes about 2.5 minutes on my Nvidia RTX 2070. (By the way, I think it would be useful to add an indication about training time in the README.)

### My configuration

- Ocaml 4.10+flambda
- CUDA 10.2
- ocaml-torch installed using he PyTorch binaries (version 1.5.0, CXX11).

**Comment by LaurentMazare** [comment]
Thanks for reporting this, I just pushed some changes that should get rid of this warning by flattening parameters when using cudnn.
Fwiw an epoch takes 2m10s on my RTX 2080 so there probably isn't much of a benefit for this (arguably small) network size.
