### ISSUE TITLE
Status of the Transformer Example

### ISSUE THREAD

**Issue by jonathan-laurent** [LaurentMazare/ocaml-torch#41]
I was wondering what the status of the transformer example was. Indeed, the model seems to be implemented in full but it comes with no demo task. From the comments, it seems that the plan was to train it on a simple copy task but this hasn't been implemented yet.

More concretely, here are my questions:

- Has the current implemented model been tested?
- Would you be interested in a demo task PR?

**Comment by LaurentMazare** [comment]
Right, this has actually never been tested and is mostly a work in progress so we should probably either remove it or get it to work.
I would be very interested in a PR getting this to work on some demo task (but I would expect a bit of model finalization/debugging to be required). A transformer implementation coded from scratch would be interesting too.

**Comment by jonathan-laurent** [comment]
Why would one want to code it from scratch rather than building on this implementation?
Is it because you think it would be possible to write it with more idiomatic OCaml code?

**Comment by LaurentMazare** [comment]
I don't think it would be better to do it from scratch, but it may be more exciting for whoever works on this to write the whole thing, so I just wanted to mention that I would be interested in this too :)

**Comment by LaurentMazare** [comment]
Just to mention that there is now a separate repo with some BERT variants [ocaml-bert](https://github.com/LaurentMazare/ocaml-bert). I've removed the transformer example from the main repo and added a link to this.
