### ISSUE TITLE
How to know the device on which a tensor is stored?

### ISSUE THREAD

**Issue by jonathan-laurent** [LaurentMazare/ocaml-torch#42]
There is a function `Tensor.to_device` to move a tensor to another device but I could not find a function `Tensor.get_device: Tensor.t -> Device.t` to know the device on which a tensor is stored.

Is there any workaround and do you think it might be worth adding such a function?

**Comment by LaurentMazare** [comment]
There wasn't a function for this but as it was straightforward to add I just pushed some changes adding it: there is now a `Tensor.device` function using the signature that you mentioned.
(the typical workaround before this would have been to use `Var_store.device` when using a variable store but that's a slightly different use case)

**Comment by jonathan-laurent** [comment]
Thanks a lot!
I have been using ocaml-torch for a week now and it is a real pleasure. :-)
