### ISSUE TITLE
cat_out unexpected result on views

### ISSUE THREAD

**Issue by mreppen** [LaurentMazare/ocaml-torch#52]
I am not familiar with the libtorch C++ API, so maybe this is not unexpected:

I noticed that `cat_out` behaves unexpectedly when combined with views:
```
# let x = T.ones [3; 2];;
val x : T.t =
 1  1
 1  1
 1  1

# let y = T.narrow ~dim:1 ~start:0 ~length:1 x;;
val y : T.t =
 1
 1
 1

# T.(y.%.{[2;0]}<-2.);;
- : unit = ()

# y;;
- : T.t =
 1
 1
 2

# x;;
- : T.t =
 1  1
 1  1
 2  1

# T.zeros_out ~out:y ~size:(T.size y);;
- : T.t =
 0
 0
 0

x;;
- : T.t =
 0  1
 0  1
 0  1
```

So the view `y` and `ones_out` are working as expected. But then with `cat_out`:

```
# T.cat_out ~out:y ~dim:1 [T.ones ~scale:3. (T.size y)];;
- : T.t =
 3
 3
 3

# x;;
- : T.t =
 3  3
 3  1
 2  1
```

In fact, `ones_out` and `zeros_out` work as expected _before_ `cat_out`, but `cat_out` changes its behavior:

```
# T.zeros_out ~out:y ~size:(T.size y);;
- : T.t =
 0
 0
 0

x;;
- : T.t =
 0  0
 0  1
 0  1

# T.ones_out ~out:y ~size:(T.size y);;
- : T.t =
 1
 1
 1

# x;;
- : T.t =
 1  1
 1  1
 0  1
```

So it seems like cat_out is modifying the view.  The `~dim:1` in `cat_out` is not relevant; the same thing happens with 0.

Is this expected?  At least to me it was not.

Full sequence of similar steps to copy into a REPL:
```
open Torch;;
module T = Tensor;;

let x = T.zeros [ 3; 2 ];;
let y = T.narrow ~dim:1 ~start:0 ~length:1 x;;
T.(y.%.{[2;0]}<-2.);;
T.ones_out ~out:y ~size:(T.size y);;
T.cat_out ~out:y ~dim:1 [T.ones ~scale:3. (T.size y)];;
T.ones_out ~out:y ~size:(T.size y);;
T.zeros_out ~out:y ~size:(T.size y);;

let y = T.narrow ~dim:1 ~start:0 ~length:1 x;;
T.zeros_out ~out:y ~size:(T.size y);;
```

Happy Holidays and thanks for releasing this! :christmas_tree:

**Comment by LaurentMazare** [comment]
Thanks for reporting this issue, indeed the behavior you observed looks quite odd. The same thing applies at the C++ level (of which this library is just a 'thin' ocaml wrapper upon). Here is a conversion of some bits of your code to illustrate this.
You should probably ask about it on the pytorch github repo. I have no clue whether this should be expected or not, maybe this is mostly a matter of the _out functions having undefined behaviors when targetting non-contiguous views (I have to say that I mostly never use _out functions).

```cpp
#include <torch/torch.h>
#include <iostream>

int main() {
  torch::Tensor x = torch::zeros({3, 2});
  torch::Tensor y = x.narrow(/*dim=*/1, /*start=*/0, /*length=*/1);
  y.index_put_({2, 0}, 2);
  std::cout << x << std::endl;
  torch::ones_out(y, {3, 1});
  std::cout << x << std::endl;
  torch::cat_out(y, {torch::ones({3, 1}) * 3.}, /*dim=*/1);
  std::cout << x << std::endl;
}
```

**Comment by mreppen** [comment]
Thanks for the C++ example. I reported it in the pytorch repo. I can update here if there are any news. But, as you say, the problem is not caused here so feel free to close.

I make a bunch of small modifications to larger tensors, so _out functions help me avoid excessive allocations.

**Comment by mreppen** [comment]
Closing because it's fixed upstream
