### ISSUE TITLE
Citing this project

### ISSUE THREAD

**Issue by Kwonsoo** [LaurentMazare/ocaml-torch#56]
Hi Laurent,

We used `ocaml-torch` in our research, and wrote a paper: https://arxiv.org/abs/2103.00737.
Right before Section 6.1, the paper cites `ocaml-torch`, but I want to double-check if that is the way of citing this project that you like.

Thanks,
Gwonsoo

**Comment by LaurentMazare** [comment]
Looks very good to me, thanks for the citation!

**Comment by Kwonsoo** [comment]
Great. Thank you very much.

Gwonsoo
