### ISSUE TITLE
Newbie question (building example) (Library not loaded: @rpath/libc10.dylib)

### ISSUE THREAD

**Issue by mfirry** [LaurentMazare/ocaml-torch#6]
Sorry I'm new to most of this (besides torch) but I wanted to give OCaml a try.

On my mac I get this while building the example.

Any clue what I'm doing wrong?

Thanks

```
❯ dune build example.bc

      ocamlc example.bc (exit 2)
(cd _build/default && /Users/pmanning/.opam/4.06.0/bin/ocamlc.opt -w @a-4-29-40-41-42-44-45-48-58-59-60-40 -strict-sequence -strict-formats -short-paths -keep-locs -g -o example.bc -I /Users/pmanning/.opam/4.06.0/lib/base -I /Users/pmanning/.opam/4.06.0/lib/base/caml -I /Users/pmanning/.opam/4.06.0/lib/base/shadow_stdlib -I /Users/pmanning/.opam/4.06.0/lib/bytes -I /Users/pmanning/.opam/4.06.0/lib/ctypes -I /Users/pmanning/.opam/4.06.0/lib/integers -I /Users/pmanning/.opam/4.06.0/lib/ocaml/threads -I /Users/pmanning/.opam/4.06.0/lib/sexplib0 -I /Users/pmanning/.opam/4.06.0/lib/stdio -I /Users/pmanning/.opam/4.06.0/lib/torch -I /Users/pmanning/.opam/4.06.0/lib/torch/core /Users/pmanning/.opam/4.06.0/lib/base/caml/caml.cma /Users/pmanning/.opam/4.06.0/lib/base/shadow_stdlib/shadow_stdlib.cma /Users/pmanning/.opam/4.06.0/lib/sexplib0/sexplib0.cma /Users/pmanning/.opam/4.06.0/lib/base/base.cma /Users/pmanning/.opam/4.06.0/lib/stdio/stdio.cma /Users/pmanning/.opam/4.06.0/lib/ocaml/unix.cma /Users/pmanning/.opam/4.06.0/lib/ocaml/bigarray.cma /Users/pmanning/.opam/4.06.0/lib/integers/integers.cma /Users/pmanning/.opam/4.06.0/lib/ctypes/ctypes.cma /Users/pmanning/.opam/4.06.0/lib/ocaml/threads/threads.cma /Users/pmanning/.opam/4.06.0/lib/ctypes/ctypes-foreign-base.cma /Users/pmanning/.opam/4.06.0/lib/ctypes/ctypes-foreign-threaded.cma /Users/pmanning/.opam/4.06.0/lib/ocaml/str.cma /Users/pmanning/.opam/4.06.0/lib/ctypes/cstubs.cma /Users/pmanning/.opam/4.06.0/lib/torch/core/torch_core.cma /Users/pmanning/.opam/4.06.0/lib/torch/torch.cma .example.eobjs/example.cmo)
File "_none_", line 1:
Error: Error on dynamically loaded library: /Users/pmanning/.opam/4.06.0/lib/stublibs/dlltorch_core_stubs.so: dlopen(/Users/pmanning/.opam/4.06.0/lib/stublibs/dlltorch_core_stubs.so, 10): Library not loaded: @rpath/libc10.dylib
  Referenced from: /Users/pmanning/.opam/4.06.0/lib/stublibs/dlltorch_core_stubs.so
  Reason: image not found
```

**Comment by LaurentMazare** [comment]
Thanks for the feedback - as per #2 macos support is pretty much a work in progress. Could you try compiling a native executable rather than a bytecode one via `dune build example.exe` and posting the output ? (`.bc` stands for bytecode)
I won't have access to a mac until the end of this week so I may have some more helpful advice at this point.

**Comment by mfirry** [comment]
So compilation seems to work (no output whatsoever) but when I run it i get `command not found: mono`. Will investigate and let you know.

**Comment by LaurentMazare** [comment]
That's very weird indeed, there shouldn't be any dependency to `mono`. Not sure how you ran the executable but you can also try `dune exec example.exe` (which will both build and run the executable) or alternatively after building use the binary from the _build directory, e.g. `./_build/default/example.exe` or something like this.

**Comment by mfirry** [comment]
Oops. My bad I have ` alias -s exe=mono` on my `.zshrc` 😆

**Comment by mfirry** [comment]
Close this if you want. Not sure you want to keep it open to work on the bytecode thing for macos

**Comment by LaurentMazare** [comment]
Glad that it worked, I've added a word of warning for this on the readme. Don't hesitate to re-open or create new issues if you have further feedback or run into any problem.
