### ISSUE TITLE
Is it possible to download pretrained model weights from the python version of pytorch and use it in ocaml-torch?

### ISSUE THREAD

**Issue by ArulselvanMadhavan** [LaurentMazare/ocaml-torch#62]
Currently, I am trying to load pretrained weights from mini-dalle using the ocaml-torch library. The examples seem to do a jit trace and save the entire model architecture with weights and load them. Is there an example where the library uses the ".pt" file saved by the pytorch and loads it into an equivalent ocaml torch model architecture?

**Comment by LaurentMazare** [comment]
It should be possible to run jit traced model that use the `.pt` format via ocaml-torch, this [example](https://github.com/LaurentMazare/ocaml-torch/blob/main/examples/jit/README.md) shows how to do this on some CV model. Some kind of model inputs may not be supported at the moment though but they should be reasonably easy to add.

**Comment by ArulselvanMadhavan** [comment]
Thank you! I will try this. I missed this example
