### ISSUE TITLE
Torch installation not working with ubuntu

### ISSUE THREAD

**Issue by ChrisRawstone** [LaurentMazare/ocaml-torch#64]
Hi I want to do ocaml torch for a project. But when I try to install it on my ubuntu sublinux system then I get the following error:

ERROR] The compilation of conf-zlib.1 failed at "pkg-config zlib"

I tried to looking at the install page website where they download it from and it simply states 404

My details are:

NAME="Ubuntu"
VERSION="20.04 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04 LTS"
VERSION_ID="20.04"

**Comment by LaurentMazare** [comment]
Hi, I don't know much about sublinux systems but my guess is that the zlib development package is missing from your system and you need to install it via something like the following ([stackoverflow link](https://askubuntu.com/questions/1169754/configure-error-could-not-find-the-zlib-library)):
```
sudo apt-get install zlib1g-dev
```

**Comment by ChrisRawstone** [comment]
Yeah it works. My bad, I am new to linux coming from windows.
