### ISSUE TITLE
Getting Issue with mnist tutorials

### ISSUE THREAD

**Issue by ChrisRawstone** [LaurentMazare/ocaml-torch#65]
Hi again,
So I have been trying to run the mnist examples in the tutorial. But when I train (linear.ml), It never improves it's accuracy. I have even tried setting it to 1000 epochs and it is still 0 accuracy. See image.

![image](https://user-images.githubusercontent.com/52676332/198846433-0eaecd76-7206-4bdf-aa96-3ad5ed8d5797.png)

When I try to run the other mnist examples (conv.ml and nn.ml) it throws a long error. see Image

![image](https://user-images.githubusercontent.com/52676332/198846594-5a2b33e4-ecae-464b-afc0-8d1625d5c359.png)

What I have done as you can see on image, is that I have made a testfolder and just put the data folder in there with the example.ml.
I have also extracted the datasets from gz format.

**Comment by LaurentMazare** [comment]
Are you using the latest github version rather than the opam package? I think the opam package still has the bug that was fixed last week so would likely not work - I just tried again the current github tip and it works well for me.

**Comment by ChrisRawstone** [comment]
I am using the latest opam package. I can try with github version but the libtorch link on the main page of your ocaml-torch page is broken. I am relatively new to ocaml and have not tried running any major libraries just from the github. 

After installing libtorch, what part of the code should I change inorder to making in run from the github instead of the opam.
When will you update the opam package? If it is within a day or two then I can just wait.

I am doing this for a final project in an ocaml course at Johns Hopkins, so would be really nice to do ml with this package.

**Comment by LaurentMazare** [comment]
I made an opam release over the week-end and the [pull request](https://github.com/ocaml/opam-repository/pull/22413) just got merged, so my guess is that by tomorrow you should have access to a version including the bugfix (0.16).

**Comment by ChrisRawstone** [comment]
Thank you! Got it working as well on the github way.

**Comment by JefferyO** [comment]
Hi, I'm also facing this issue of always zero accuracy when running linear.ml 
I'm using the opam package:
<img width="1046" alt="48e3e7cf888554ad7c698208d070e53" src="https://github.com/LaurentMazare/ocaml-torch/assets/40513972/6a4770ab-f794-44ec-80cd-a390ecf0412c">

And even the sample utop in Readme is not working:
<img width="312" alt="108daac99d00c245c767686c3b6e312" src="https://github.com/LaurentMazare/ocaml-torch/assets/40513972/6a6497f6-5874-450d-8425-a6059a2442d0">

Any help will be greatly appreciated!
