### ISSUE TITLE
Is there anthing equivalent to load and save model in ocaml torch

### ISSUE THREAD

**Issue by ChrisRawstone** [LaurentMazare/ocaml-torch#66]
Hi again,
I was browsing your library looking for load and save bindings for saving and loading a model. 
I may have missed it, but in the case you got bindings for it, is it possible to make small tutorial using it?

Bonus question:
I see you have a function that turns in a tensor to a list. But do you have a function turning a list into a tensor?
Same goes for the ocaml arrays. Do you have a function that a tensor into an array and reverse?

**Comment by LaurentMazare** [comment]
I'm not sure to understand what you mean by "saving and loading a model". Is it about serializing the weights or the full model architecture. Both are somehow supported, to save load tensors you can find a bunch of examples in the codebase, e.g. [here](https://github.com/LaurentMazare/ocaml-torch/blob/a82b906a22c7c23138af16fab497a08e5167d249/src/tests/serialization_tests.ml) for tensor serialization. Models typically store their weights in a `Var_store.t` and these get serialized through the same api, e.g. [here](https://github.com/LaurentMazare/ocaml-torch/blob/a82b906a22c7c23138af16fab497a08e5167d249/examples/yolo/yolo.ml#L136). Finally see this [tutorial](https://github.com/LaurentMazare/ocaml-torch/tree/main/examples/jit) for the full model via the jit layer.

For converting list/array to tensors, there are a bunch function doing so, maybe have a look at the tests in this [file](https://github.com/LaurentMazare/ocaml-torch/blob/46df099de0ba5f1ab92d2ca1fe8b6c5f25a0db62/src/tests/tensor_tests.ml#L77) to get a feeling of what is available.

**Comment by ChrisRawstone** [comment]
This what exactly what I meant. But for the saving and loading a model. Your example shows you loading a python torch trained model. My project has to be done solely in ocaml. Is this library capable of saving a model and loading a model using only ocaml?

I guess what I am looking for It pretty well demonstrated by this tensorflow (I know we are using torch;) )
![image](https://user-images.githubusercontent.com/52676332/199889850-0a3416d3-0d6e-48ec-87f2-92b17e9eeec3.png)

https://keras.io/guides/serialization_and_saving/

**Comment by LaurentMazare** [comment]
You can save all the tensor values saved in a `Var_store.t` and load them, all this via the `Serialized` api (see the yolo example from my previous message for loading the weights, writing them is similar). Note that there is no way to serialize the model architecture so the yolo code generates the model then load the weights - but if your code is fully in ocaml this should not be an issue.

**Comment by ChrisRawstone** [comment]
Thank you for your very detailed responses. Using your responses I was able to do everything in your library that I needed for my project. Hopefully these discussions will be able to help others.
