### ISSUE TITLE
Support for CUDA 11

### ISSUE THREAD

**Issue by ArulselvanMadhavan** [LaurentMazare/ocaml-torch#68]
I have been working on porting mini-dalle using ocaml-torch. I just realized that the GPU I have doesn't support CUDA 10.2. Any plans on upgrading this library to CUDA 11.x versions? What would happen if I try to run this library with libtorch compiled for cuda 11.x ?

**Comment by ArulselvanMadhavan** [comment]
Also, the link to download cuda 10.2 version of libtorch is no longer working. It leads to access denied page

**Comment by LaurentMazare** [comment]
Cuda 11 should be supported out of the box (none of the code in `ocaml-torch` is specific to a cuda version). Thanks for pointing out the broken link, it's now fixed and recommends using 11.7 (but it should work with the other libtorch versions available on the main [pytorch.org website](https://pytorch.org/get-started/locally/)).

**Comment by ArulselvanMadhavan** [comment]
Thank you
