### ISSUE TITLE
Mini-Dalle Example

### ISSUE THREAD

**Issue by ArulselvanMadhavan** [LaurentMazare/ocaml-torch#70]
Thanks for this library and answering my questions over the last week or so! I finished writing mini-dalle inference path in OCaml. I wanted to see if you would be interested in linking this project as an example here.

https://github.com/ArulselvanMadhavan/mini_dalle

**Comment by LaurentMazare** [comment]
Wow, congrats that looks very nice, I've added a reference to it in the main readme. I would encourage you to advertise this if you haven't done so already, I think lots of folks would find it interesting.
The ocaml [discourse](https://discuss.ocaml.org/) might be a good place for this as well as the usual [reddit](https://www.reddit.com/r/ocaml/) or twitter.

**Comment by ArulselvanMadhavan** [comment]
Thanks for adding the link to my repo! I made the announcement on discourse and reddit. Looking forward to trying out this library more!
