### ISSUE TITLE
How to load a npz file to a tensor?

### ISSUE THREAD

**Issue by ChrisRawstone** [LaurentMazare/ocaml-torch#71]
Hi, I am sorry if this is really obvious but what I want is to get the npz file stored as a tensor. I have looked at your examples and tried running them but gives me an error message, see image. I use numpys functions to generate a npz. I have also tried with npy as you can see in the image.
I also think the function on the picture does something else than what I want. But I have just become really stubborn on getting it to work properly.
I guess what I really want is something that does this:
filename.npz -> tensor

So you are able to do:
let testimage = tensor(load(file.npz))

Do you have something that does that in your library?

In case you want to know what the full "ls" is on the picture then:
let () = ls ["/mnt/c/Users/Rawstone/OneDrive/Dokumenter/Skole/Universitet/5Semester/FunctionalProgramming/FPSE-FinalProject/MLtest/handwrittenImage.npz"];;

![image](https://user-images.githubusercontent.com/52676332/200990106-67cc2989-7164-47f3-8d21-a28b9bea1264.png)

**Comment by LaurentMazare** [comment]
Hello, looking at the error message in your screenshot, the error seems to come from [this line of npy-ocaml](https://github.com/LaurentMazare/npy-ocaml/blob/1174e046845bace65b2ca49be5d35a1f0ed9604a/src/npy.ml#L244). The npy file encodes the endianness as `<` for little-endian, `>` for big-endian, `=` for platform native and `|` for types where endianness is not applicable (see the [numpy doc here](https://numpy.org/doc/stable/reference/generated/numpy.dtype.byteorder.html#numpy.dtype.byteorder)).
What is the dtype of the tensor that you're trying to read? If it's a float32 or float64, I'm not sure to understand what is going on here, if it's a char/i1/u1 that would explain why `|` is used and that's a bug on the `npy-ocaml` side (which is straightforward to fix).
You can check the type on the python side by looking at `mynparray.dtype` and `mynparray.dtype.byteorder`.

**Comment by ChrisRawstone** [comment]
Hi again. Thanks for responding so quickly. Yes the issue was that it was uint8. Changing it to float fixed the problem.

Now where that is working. I am still trying to load a npz file (that contains the image) into ocaml such that I can perform functions on it.
From looking at your tensor_tools.ml it seems like there they all just print a unit or saves the tensor in an another destination. But what I would like is to load the npz and just save it as a tensor somewhere. 
Another solution could be to save it as tensor and then load the tensor if you have a function for that?

let testimage = tensor(load(file.npz))

Do you have something that does that in your library?
![image](https://user-images.githubusercontent.com/52676332/201441157-6bbc8787-755a-4794-9a53-d722c1b8490c.png)
