### ISSUE TITLE
Setting slices of a tensor: what is the equivalent of (python) x[i,:,:] = y

### ISSUE THREAD

**Issue by tlh24** [LaurentMazare/ocaml-torch#74]
I spent some time grepping through the (autogenerated) source, and think it's some sort of _input_put* function, but can't seem to figure out exactly what or how to do the slicing/indexing. 
In Python it would be: 

    x = torch.zeros(1000, 30, 30)
    y = torch.randn(30, 30)
    x[5,:,:] = y

or perhaps

    x = torch.zeros(1000, 60, 60)
    y = torch.randn(30, 30)
    i = 5
    x[5,30:,25:-5] = y

Posting here in case others have the same simple question.  

Anyway, this is a great library, thank you very much for all the hard work!!

**Comment by LaurentMazare** [comment]
You can probably do this via a combination of `Tensor.narrow` or `Tensor.index` to select on the appropriate indexes and extract a "subtensor" and then use `Tensor.flll_float` on this. E.g. here is some code doing this in the [char-rnn example](https://github.com/LaurentMazare/ocaml-torch/blob/05dd3a738fa63bde29c25b1315dd0e965fce80a6/examples/char_rnn/char_rnn.ml#L25).
```ocaml
Tensor.fill_float (Tensor.narrow prev_y ~dim:1 ~start:prev_label ~length:1) 1.;
```
This would be equivalent to `prev_y[:,prev_label,..] = 1` on the python side.

**Comment by tlh24** [comment]
Makes sense -- but what if the RHS is a tensor, not a const float?

**Comment by LaurentMazare** [comment]
I haven't tried but my guess is that you would want `Tensor.copy_` there, e.g.:
```ocaml
Tensor.copy_ (Tensor.narrow prev_y ~dim:1 ~start:prev_label ~length:1) ~src:my_src_tensor;
```

**Comment by LaurentMazare** [comment]
I would think that:
- `Tensor.copy src` would create a deep copy of tensor `src`.
- `Tensor.copy_ dst ~src` would copy the content of `src` into `dst`. The internal convention of PyTorch is that names ending with `_` mean that it modifies the original tensor.
-  I'm not really sure what `Tensor.copy_out` is doing, it's an override of the `copy` method of the C++ api, you can see its definition in [Declarations-v1.13.0.yaml](https://github.com/LaurentMazare/ocaml-torch/blob/main/third_party/pytorch/Declarations-v1.13.0.yaml). Seems pretty similar to `Tensor.copy_` from what I see there.

**Comment by LaurentMazare** [comment]
Closing this for now but feel free to re-open if you run into further issues.

**Comment by tlh24** [comment]
Sure thing.

If I feel compelled, may see if some syntactic sugar can be made for this
use-case, but for now it works well.
