### ISSUE TITLE
.pt file to .ot file - Anyway to skip the conversion

### ISSUE THREAD

**Issue by ArulselvanMadhavan** [LaurentMazare/ocaml-torch#80]
I have an OCaml program that usually reads ".ot" file as input. The files are just raw tensors. No other information is in there. Is there a way to make it also support ".pt" file without having to convert to ".npz"?

**Comment by LaurentMazare** [comment]
Do you want to try the new `load_from_pt` function from #82 (note that this is the new libtorch 2.0.0 version). It works on some pt files but is sadly far from perfect and you may run into some "Expected GenericDict but got None" error, see https://github.com/LaurentMazare/tch-rs/issues/595 for some discussion around these issues (the same mechanism is used in the rust version).
If you can change the python code writing the weights, it's easy to get around via something like:
```python
torch.save(dict(model.state_dict()), "mymodel.pt")
```

**Comment by ArulselvanMadhavan** [comment]
Reverted to HEAD~1 and tried to ocaml-torch with libtorch 1.13. It works. So, it's just the libtorch 2.0 + ocaml-torch#main that has this problem

**Comment by LaurentMazare** [comment]
That's odd, the [PR adding libtorch 2.0.0](https://github.com/ocaml/opam-repository/pull/23590) was merged yesterday and after that the package was available (and used in the ocaml-torch CI when merging in the support for 2.0.0, see [here](https://github.com/LaurentMazare/ocaml-torch/actions/runs/4556426143/jobs/8036762941) where ` 2.0.0+macos-x86_64` got installed). However doing an `opam update` this morning I also don't see the 2.0.0 versions. Let's maybe wait for a day or two and hopefully it's just a transient issue with the opam index.

**Comment by LaurentMazare** [comment]
Looks like the 2.0.0 version is back in opam ([here](https://opam.ocaml.org/packages/libtorch/)), so feel free to give this a try when you get a chance.

**Comment by ArulselvanMadhavan** [comment]
I'm able to run the Serialize.load_all_pt function now but I get the error from accessing a pt file saved as an ordered_dict. I have several model state_dict(ordered_dict) in pt format that I need to go and change to dict, to test out this function in a meaningful way. I will update in a day or two.

**Comment by ArulselvanMadhavan** [comment]
I tried to use the  new function but got a new error

```bash
quantviz: internal error, uncaught exception:
          (Failure
             "Expected Tensor but got GenericList\
            \nException raised from reportToTensorTypeError at ../aten/src/ATen/core/ivalue.cpp:950 (most recent call first):\
            \nframe #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x6b (0x7f6a7ee5a6bb in /home/arul/dev/libtorch/lib/libc10.so)\
            \nframe #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0xbf (0x7f6a7ee555ef in /home/arul/dev/libtorch/lib/libc10.so)\
            \nframe #2: c10::IValue::reportToTensorTypeError() const + 0x64 (0x7f6a68007f84 in /home/arul/dev/libtorch/lib/libtorch_cpu.so)\
            \nframe #3: <unknown function> + 0x4ed0fd8 (0x7f6a6b8d0fd8 in /home/arul/dev/libtorch/lib/libtorch_cpu.so)\
            \nframe #4: torch::jit::_load_parameters(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, c10::optional<c10::Device>) + 0x57 (0x7f6a6b8d1677 in /home/arul/dev/libtorch/lib/libtorch_cpu.so)\

```

**Comment by ArulselvanMadhavan** [comment]
After removing the python list in the dict, I was able to load the "pt" file without having to convert to "ot" file.

**Comment by ArulselvanMadhavan** [comment]
Looks like as long as the state dict is {"key" : torch.Tensor, "key2": torch.Tensor} we can skip the "ot" file conversion

**Comment by LaurentMazare** [comment]
Makes sense, I guess for arbitrary python values, this would require a python runtime to evaluate them whereas dictionary of tensors only require the C++ bits. Anyway I'll merge the PR adding support for these files so that you can start using it if it's helpful.

**Comment by ArulselvanMadhavan** [comment]
Thank you @LaurentMazare! I do find this useful for my work
