### ISSUE TITLE
Compile from source with pre-built libtorch

### ISSUE THREAD

**Issue by NTT123** [LaurentMazare/ocaml-torch#9]
Hi, Thank you for a great library.

I've tried to build with pyTorch pre-built binaries (for GPU support). It was working few days ago. However, this morning I've got the following messages. My guess is that there is some changes in the latest pre-buit libtorch. 

```
### output ###
#   ocamlmklib src/wrapper/dlltorch_core_stubs.so,src/wrapper/libtorch_core_stubs.a (exit 2)
# (cd _build/default && /root/.opam/default/bin/ocamlmklib.opt -g -o src/wrapper/torch_core_stubs src/wrapper/torch_stubs.o src/wrapper/torch_api.o -lstdc++ -Wl,-rpath,/root/.opam/default/lib/libtorch/lib -L/root/.opam/default/lib/libtorch/lib -lc10 -lcaffe2 -ltorch -Wl,-rpath,/usr/local/cuda/lib64 -L/usr/local/cuda/lib64 -lcuda -lnvrtc)
# /usr/bin/ld: src/wrapper/torch_api.o: relocation R_X86_64_PC32 against symbol `_ZN3c10eqERKNS_12TensorTypeIdES2_' can not be used when making a shared object; recompile with -fPIC
# /usr/bin/ld: final link failed: Bad value
# collect2: error: ld returned 1 exit status

```

**Comment by LaurentMazare** [comment]
Hi,
Not sure what could have caused this. Just in case I added the "-fPIC" option when building the C++ wrappers. Could you give it another try with the latest github version ?
Also I've been mostly using the stable 1.0.0 and 1.0.1 versions (which I built from source). Just in case you can find the stable cuda version at the following link for cuda 9.0 on linux:
https://download.pytorch.org/libtorch/cu90/libtorch-shared-with-deps-1.0.0.zip

**Comment by NTT123** [comment]
It worked. Thank you very much!
